sudo: required
services:
  - docker

before_install:
  - docker build -t damintu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run damintu/react-test npm test -- --coverage

after_success:
  - docker build -t damintu/lab-multi-client ./client
  - docker build -t damintu/lab-multi-nginx ./nginx
  - docker build -t damintu/lab-multi-server ./server
  - docker build -t damintu/lab-multi-worker ./worker
#push to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push damintu/lab-multi-client
  - docker push damintu/lab-multi-nginx
  - docker push damintu/lab-multi-server
  - docker push damintu/lab-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: elasticbeanstalk-eu-west-3-733582062606
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
